<?php
/**
 * MyBB Copyright 2014 MyBB Group, All Rights Reserved
 *
 * Website: https://mybb.com
 * License: https://mybb.com/about/license
 *
 */

// --------------------------------------------------------------------------------
// MyBB Language Pack File.
// This file has been generated by MyBB - buildin language pack editor.
// ================================================================================
// Friendly name of the language : English (American)
// Author of the language pack : MyBB Group
// Language pack translators website : https://mybb.com/
// Compatible version of MyBB : 1818
// Last edited in MyBB Editor by : admin
// Last edited date : Thu, 15 Nov 2018 19:10:48 +0000
// --------------------------------------------------------------------------------

$l['ougc_customlang'] = 'OUGC Custom Language';
$l['theme_bootbb_header_toggle'] = 'Toggle navigation';
$l['theme_bootbb_header_forum'] = 'Forum';
$l['theme_bootbb_header_misc'] = 'Misc';
$l['theme_bootbb_boardstats_threads'] = 'Threads';
$l['theme_bootbb_boardstats_posts'] = 'Posts';
$l['theme_bootbb_boardstats_users_online'] = 'Users Most online';
$l['theme_bootbb_boardstats_users'] = 'Users'; 
$l['theme_bootbb_stats_top_poster'] = 'Today\'s top poster';
$l['theme_bootbb_stats_popular_forum'] = 'Most popular forum';
$l['theme_bootbb_stats_posts'] = 'posts';
$l['theme_bootbb_stats_threads'] = 'threads'; 
$l['theme_bootbb_footer_about_title'] = 'About Our Community';
$l['theme_bootbb_footer_about_text'] = 'Discuss about various topics in our community and have fun while doing so. Welcome to';
$l['theme_bootbb_footer_quicklinks'] = 'Quick Links';
$l['theme_bootbb_footer_facebook'] = 'Become a Fan';
$l['theme_bootbb_footer_twitter'] = 'Follow Us';
$l['theme_bootbb_footer_reachus'] = 'Reach Us';
$l['theme_bootbb_forumdisplay_rss'] = 'RSS Feed';
$l['welcome_newposts'] = 'New Posts';
$l['welcome_todaysposts'] = 'Today\'s Posts';
$l['toplinks_memberlist'] = 'Members';

